### ISSUE TITLE
panicked on `read_builtins` when `output` builtin used

### ISSUE THREAD

**Issue by tdelabro** [maxgillett/giza#12]
Here is my code:

```cairo
%builtins output 

func main{output_ptr: felt*}():

    [ap] = 4
    [ap] = [output_ptr]; ap++ 
    
    let output_ptr = output_ptr + 1
    return ()
end
```

Here are the commands I run:
```shell
$ cairo-compile program.cairo --output program.json
$ cairo-run --program=check_hash_compiled.json --layout=all --memory_file=memory.bin --trace_file=trace.bin --print_output
Program output:
  4
$ giza prove --trace=trace.bin --memory=memory.bin --program=program.json --output=output.bin                 
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', runner/src/cairo_interop.rs:95:57
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This is the function panicking:
```rust
pub fn read_builtins(program_path: &PathBuf, output_len: Option<u64>) -> Vec<Builtin> {
    // Read compiled program and set memory codelen (the length of the public memory)
    let file = File::open(&program_path).expect("Compiled program file not found");
    let reader = BufReader::new(file);
    let p: CompiledProgram = serde_json::from_reader(reader).unwrap();
    let builtins = p
        .builtins
        .iter()
        .filter_map(|b| match b.as_str() {
            "output" => Some(Builtin::Output(output_len.unwrap())),
            _ => None,
        })
        .collect::<Vec<_>>();
    builtins
}
```
It unwrap `output_len` which is none.

**Comment by tdelabro** [comment]
```shell
giza prove --trace=trace.bin --memory=memory.bin --program=program.json --output=output.bin --output_len=1
error: Found argument '--output_len' which wasn't expected, or isn't valid in this context

        Did you mean '--output'?

        If you tried to supply `--output_len` as a value rather than a flag, use `-- --output_len`

USAGE:
    giza prove --program <PROGRAM> --trace <TRACE> --memory <MEMORY> --output <OUTPUT>

For more information try --help
```

```
giza prove --trace=trace.bin --memory=memory.bin --program=program.json --output=output.bin --help               
giza-prove 0.1.0

USAGE:
    giza prove [OPTIONS] --program <PROGRAM> --trace <TRACE> --memory <MEMORY> --output <OUTPUT>

OPTIONS:
    -h, --help                         Print help information
        --memory <MEMORY>              Path to the memory output file
        --num-outputs <NUM_OUTPUTS>    Number of serialized outputs
        --output <OUTPUT>              Path to write the STARK proof
        --program <PROGRAM>            Path to the compiled Cairo program JSON file
        --trace <TRACE>                Path to the execution trace output file
    -V, --version                      Print version information
```

are you talking about `--num-outputs` ?

**Comment by maxgillett** [comment]
Yes, my mistake, `--num-outputs`.

The error you're getting now is due to the number of FRI queries being larger than the size of the LDE execution trace. There are a couple of ways to fix this:
- Decrease the number of FRI queries (the first argument to the WinterProofOptions constructor), or 
increase the blowup factor (the second argument). Changing it to 27 and 8 should work, and give you the same 96 bits of security. These proof options should really be exposed in the CLI and not hardcoded. https://github.com/maxgillett/giza/blob/ce65e652d02fd7995cfca4bf76ca7b592bbc1813/air/src/options.rs#L31-L41
- Pad the execution trace to a minimum length. This could be done by modifying the `resize_to_pow2` function.
https://github.com/maxgillett/giza/blob/ce65e652d02fd7995cfca4bf76ca7b592bbc1813/runner/src/trace.rs#L427

**Comment by tdelabro** [comment]
Ok it worked by changing the number of FRI.

I can probably do a PR exposing those proof options in the CLI. Is there ony two options ? 54/4 and 27/8 ? Or should we provide the user with ability to chose any value for those arguments ?

**Comment by maxgillett** [comment]
Great, that would be really helpful. There are several options, and you can find the constraints on their possible values here:
https://docs.rs/winterfell/latest/winterfell/struct.ProofOptions.html#impl. I'm thinking we can have the current options given as defaults so that the flags are optional. The only option we shouldn't expose is the field extension, which can be left at `FieldExtension::None`.
